version: "3"
services:
  database:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hFwI/MvZJJ[Y2WBq£1,(BN8\[-8Yu5^
    volumes:
      - elof_database:/var/lib/postgresql/data3
    networks:
      scavenger-hunt:
        aliases:
          - database

  web:
    restart: always
    build: ./server
    command: /app/entrypoint.sh
    environment:
      - DATABASE_URL=postgresql://postgres:hFwI/MvZJJ[Y2WBq£1,(BN8\[-8Yu5^@45.95.234.124:9856/scavenger_hunt
      - BOT_TOKEN=6652038217:AAEY0Znq7UHaM4aP7WF8ZXnP6Ef99sFd-B4
      - CHAT_IDS=-695909740
    #      - DATABASE_URL=postgresql://postgres:hFwI/MvZJJ[Y2WBq£1,(BN8\[-8Yu5^@database/scavenger_hunt
    ports:
      - "6890:8000"
    networks:
      scavenger-hunt:
        aliases:
          - web

  front:
    restart: always
    ports:
      - "9131:80"
    environment:
#      - VITE_API_URL=https://scavenger-hunt.elephahealth.com/
      - VITE_API_URL=http://localhost:6890/
    build:
      context: ./client
      dockerfile: ./Dockerfile

volumes:
  elof_database:

networks:
  scavenger-hunt:
