"""empty message

Revision ID: 1a6a2325ac11
Revises: 
Create Date: 2023-04-09 01:46:56.315456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a6a2325ac11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__results')),
    sa.UniqueConstraint('id', name=op.f('uq__results__id'))
    )
    op.create_table('solved_quiz',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__solved_quiz')),
    sa.UniqueConstraint('id', name=op.f('uq__solved_quiz__id'))
    )
    op.create_table('solved_tasks',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__solved_tasks')),
    sa.UniqueConstraint('id', name=op.f('uq__solved_tasks__id'))
    )
    op.create_table('task',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.Column('flag', sa.TEXT(), nullable=True),
    sa.Column('with_manager', sa.BOOLEAN(), nullable=False),
    sa.Column('manager_id', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('usage', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__task')),
    sa.UniqueConstraint('flag', name=op.f('uq__task__flag')),
    sa.UniqueConstraint('id', name=op.f('uq__task__id')),
    sa.UniqueConstraint('name', name=op.f('uq__task__name'))
    )
    op.create_table('team',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('member_number', sa.INTEGER(), nullable=True),
    sa.Column('visible', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__team')),
    sa.UniqueConstraint('id', name=op.f('uq__team__id')),
    sa.UniqueConstraint('name', name=op.f('uq__team__name')),
    sa.UniqueConstraint('token', name=op.f('uq__team__token'))
    )
    op.create_table('user',
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__user')),
    sa.UniqueConstraint('chat_id', name=op.f('uq__user__chat_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('task')
    op.drop_table('solved_tasks')
    op.drop_table('solved_quiz')
    op.drop_table('results')
    # ### end Alembic commands ###
