"""empty message

Revision ID: f05c02be4cc1
Revises: 1a6a2325ac11
Create Date: 2023-04-09 01:47:31.732052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05c02be4cc1'
down_revision = '1a6a2325ac11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__results__id'), 'results', ['id'])
    op.create_unique_constraint(op.f('uq__solved_quiz__id'), 'solved_quiz', ['id'])
    op.create_unique_constraint(op.f('uq__solved_tasks__id'), 'solved_tasks', ['id'])
    op.create_unique_constraint(op.f('uq__task__id'), 'task', ['id'])
    op.create_unique_constraint(op.f('uq__team__id'), 'team', ['id'])
    op.create_unique_constraint(op.f('uq__user__chat_id'), 'user', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user__chat_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq__team__id'), 'team', type_='unique')
    op.drop_constraint(op.f('uq__task__id'), 'task', type_='unique')
    op.drop_constraint(op.f('uq__solved_tasks__id'), 'solved_tasks', type_='unique')
    op.drop_constraint(op.f('uq__solved_quiz__id'), 'solved_quiz', type_='unique')
    op.drop_constraint(op.f('uq__results__id'), 'results', type_='unique')
    # ### end Alembic commands ###
