"""empty message

Revision ID: fa336814cae8
Revises: 43358d0f3135
Create Date: 2024-04-07 13:38:50.328498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa336814cae8'
down_revision = '43358d0f3135'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solved_quiz', sa.Column('points', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solved_quiz', 'points')
    # ### end Alembic commands ###
