"""empty message

Revision ID: 43358d0f3135
Revises: 0a9f4f35d4aa
Create Date: 2024-03-26 15:51:00.705117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43358d0f3135'
down_revision = '0a9f4f35d4aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
