"""empty message

Revision ID: e48389c3f35f
Revises: fa336814cae8
Create Date: 2024-04-10 09:56:46.576488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48389c3f35f'
down_revision = 'fa336814cae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solved_quiz', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solved_quiz', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
