"""empty message

Revision ID: 0a9f4f35d4aa
Revises: f05c02be4cc1
Create Date: 2024-03-25 20:08:40.198902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9f4f35d4aa'
down_revision = 'f05c02be4cc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
